### ISSUE TITLE
swimmyのrestartをコマンドで実行できるようにする

### ISSUE THREAD

**Issue by fujiwara-yu** [nomlab/swimmy#45]
Created from [AI0691](http://jay.swlab.cs.okayama-u.ac.jp/minutes/956?ai=0691) of minute 956.
+ swimmyのrestartをコマンドで実行できるようにする．-->(藤原 !:0691)

**Comment by fujiwara-yu** [comment]
swimmyはsystemdを用いて起動している．このため，再起動には，systemdのrestartコマンドを用いる必要がある．
現在，以下の方法を検討している．
+ systemdのrestartコマンドを実行できるShellスクリプトを作成する．
+ swimmyにrestartコマンドを作成し，swimmyのrestartコマンドが実行されれば，Shellスクリプトが実行され，swimmyが再起動するようにする．

**Comment by fujiwara-yu** [comment]
## 現状
藤原のローカル環境にて起動し，restartコマンド実行後に再起動していることを確認した．
しかし，systemdで実行したswimmyにて動作確認を行っていない．
今後は，systemdで実行したswimmyの動作確認を行い，PRを作成する．

## ソースコード
`restart.rb`
```
     1  # coding: utf-8
     2
     3  module Swimmy
     4    module Command
     5      class Restart < Swimmy::Command::Base
     6
     7        command "restart" do |client, data, match|
     8          client.say(channel: data.channel, text: "再起動します")
     9
    10          begin
    11            exe_file = Dir::pwd + "/exe/swimmy"
    12            exec("bundle exec #{exe_file}")
    13          rescue => e
    14            client.say(channel: data.channel, text: "再起動に失敗しました．")
    15            raise e
    16          end
    17        end
    18
    19        help do
    20          title "restart"
    21          desc "swimmyを再移動します．"
    22          long_desc "swimmyを再起動します．引数はありません．"
    23        end
    24
    25      end # class Restart
    26    end # module Command
    27  end # module Swimmy
```

**Comment by fujiwara-yu** [comment]
systemdでswimmyｗ実行し，上記のプログラムを追加してrestartを試した．
結果としては，無事に再起動された．

#56 完成後にswimmyの起動オプションを用いて再起動するように変更して，PRを出す．

**Comment by miyake13000** [comment]
restart コマンドがマージされたため，クローズする．
