### ISSUE TITLE
swimmy起動時に，指定したメッセージをSlackに通知するためのオプションを実装する

### ISSUE THREAD

**Issue by fujiwara-yu** [nomlab/swimmy#56]
Created from [AI0699](http://jay.swlab.cs.okayama-u.ac.jp/minutes/967?ai=0699) of minute 967.
+ swimmy起動時に，指定したメッセージをSlackに通知するためのオプションを実装する．-->(藤原 !:0699)

**Comment by miyake13000** [comment]
PRがマージされたためクローズする．
