### ISSUE TITLE
swimmy起動時に，指定したメッセージをSlackに通知するためのオプションを実装する

### ISSUE THREAD

**Issue by takaie** [nomlab/swimmy#60]
Created from [AI0699](http://jay.swlab.cs.okayama-u.ac.jp/minutes/978?ai=0699) of minute 978.
+ swimmy起動時に，指定したメッセージをSlackに通知するためのオプションを実装する．-->(藤原 !:0699)

**Comment by miyake13000** [comment]
#56 の Issue と内容が被っているためクローズする．
