### ISSUE TITLE
Dockerfile を作成する．

### ISSUE THREAD

**Issue by sakamoto-a** [nomlab/swimmy#68]
Created from [AI0703](http://jay.swlab.cs.okayama-u.ac.jp/minutes/1000?ai=0703) of minute 1000.
+ swimmy について Dockerfile を作成する．-->(高家，坂本，野村 !:0703)

**Comment by hamamoto-j** [comment]
#69 のPRについて
一旦マージしたが，[議事録](http://jay.swlab.cs.okayama-u.ac.jp/minutes/1034)を参考に修正し，再度PRを出す．

**Comment by miyake13000** [comment]
修正がマージされたため，クローズする．
