### ISSUE TITLE
at コマンドの仕様について考える

### ISSUE THREAD

**Issue by hamamoto-j** [nomlab/swimmy#92]
Created from [AI0775](http://jay.swlab.cs.okayama-u.ac.jp/minutes/1146?ai=0775) of minute 1146.
+ at コマンドの仕様について考える． -->(濵本，三宅 !:0775)

**Comment by hamamoto-j** [comment]
`at 時刻 do xxx ` という形式で，swimmy 自身が swimmy のコマンドを実行できるようにする．

**Comment by miyake13000** [comment]
上記のPRについてバグが発生

### バグの詳細
#### 発生条件
 全てのコマンドで発生
#### 内容
繰り返しを指定したコマンドが，初回実行時から tick がまわってくるたびに連続して実行される．

**Comment by yoshinari-nomura** [comment]
マージしたので一旦閉じます．
